suorganizer/suorganizer/urls.py
from django.contrib import admin
from django.urls import path

from organizer.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage),
]

suorganizer/blog/models.py
from django.db import models
from organizer.models import Startup, Tag

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(
        max_length=63,
        help_text='A label for URL config',
        unique_for_month='pub_date'
)
    text = models.TextField()
    pub_date = models.DateField(
        'date published',
        auto_now_add=True
)
    tags = models.ManyToManyField(
        Tag, related_name='blog_posts'
)
    startups = models.ManyToManyField(
        Startup, related_name='blog_posts')
    def __str__(self):
        return "{} on {}".format(
            self.title, self.pub_date.strftime('%Y-%m-%d'))
    class Meta:
        verbose_name = 'blog_post'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'

suorganizer/organizer/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    name = models.CharField(
        max_length=31, unique=True)
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for URL config.')
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']

class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(max_length=31, unique=True,
        help_text='A label for URL config')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField()
    link = models.URLField(max_length=255 )
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE)
    pub_date = models.DateField('date published')
    def __str__(self):
        return "{}:{}".format(
            self.startup, self.title)
    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

suorganizer/blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

suorganizer/blog/views.py
from django.shortcuts import render

# Create your views here.

suorganizer/organizer/views.py
from django.http.response import HttpResponse

from .models import Tag, Startup, NewsLink

def homepage(request):
    tag_list = Tag.objects.all()
    startup_list = Startup.objects.all()
    output = ", ".join([tag.name for tag in tag_list])
    output = output + '<br>'
    output = output + ", ".join([startup.name for startup in startup_list])
    output = output + '<br>'
    return HttpResponse(output)

suorganizer/organizer/templates/organizer/tag_detail.html
    <h2> {{ tag.name }} </h2>
      <section>
        <h3>Startups</h3>
          <ul>
            {% for startup in tag.startup_set.all %}
              <li><a href="">
                {{ startup.name }}
              </a></li>
            {% endfor %}
          </ul>
      </section>
          <section>
            <h3>Blog Posts</h3>
            <ul>

            </ul>
          </section>

suorganizer/templates/base.html
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<title>Crypto Compare</title>
</head>
<body>


<!--start scripts-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>